name: makedoc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools, covr, pkgdown

      - name: Build site
        run: Rscript -e 'pkgdown::build_site()'

      - name: Set up Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Fetch remote branches
        run: git fetch --all

      - name: Check out main branch
        run: |
          git checkout main  # Now we can safely check out the main branch

      - name: Commit and push docs to main branch
        run: |
          git add docs/
          git commit -m "Update docs with the latest changes"
          git push https://x-access-token:${{ secrets.PAGES_TOKEN }}@github.com/DSCI-310-2025/dataletes.git main
