name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("devtools", "remotes", "covr"), repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run tests and upload coverage
        run: |
          Rscript -e 'devtools::load_all()'
          Rscript -e 'devtools::test()'
          Rscript -e 'covr::codecov()'
