name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages("covr")
          install.packages("devtools")
          remotes::install_deps()
      - name: Run tests and calculate coverage
        run: |
          Rscript -e 'covr::codecov()'
          Rscript -e 'load_all()'
          Rscript -e 'test()'
